// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldtaveitfkiniibwebhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdGF2ZWl0ZmtpbmlpYndlYmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Njg0OTgsImV4cCI6MjA2NzQ0NDQ5OH0.gWK2v7Vm__4pXvNQufyMe9_aoin-OiLv6Rf1oMsmmI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});